variable "environment" {}
variable "project" {}
variable "owner" {}
variable "location" {}
variable "rg" {}
variable "subnet_id" {}
variable "hostname" {}
variable "username" {}
variable "password" {}
variable "type" {}